### PR TITLE
image size reduced and compressed

### PR DESCRIPTION
**Pull request by Shyam3050**
issue No : #92

### CODE REVIEW

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Thanks for compressing them

**Comment by Susmita-Dey** [comment]
@Shyam3050 Kindly update your branch. Then ping me. I'll merge after that.

**Comment by Shyam3050** [comment]
i already updated

**Comment by Susmita-Dey** [comment]
> i already updated

Thanks

**Pull request merged**
