### PR TITLE
Added animations and modified footer

### PR DESCRIPTION
**Pull request by sumitkr2000**
Hey @Susmita-Dey This is pull request with reference to issue no #77 . I have added animations and modified the footer as it was misaligned with the page. You can watch the screenshots below for a better idea .

- Before:-

Screenshot (366)

- After:-

(Footer)

Screenshot (367)

(Animations)

[screen-capture.webm](https://user-images.githubusercontent.com/100675296/194323229-026a77ca-22a2-4fff-aad8-a65924ab702e.webm)

Hope you like it.  Thank you!

### CODE REVIEW

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Fix merge conflicts

**Comment by sumitkr2000** [comment]
Hey, @Susmita-Dey I have successfully resolved the merge conflicts. I have solved the issue that I stated above. Please review my pull request. Thank you!

**Comment by Susmita-Dey** [comment]
@sumitkr2000 Conflicts again. Why did you change the contact us bg img?

**Comment by sumitkr2000** [comment]
@Susmita-Dey Wait ill resolve them. I haven't changed it, I was just trying to see if it looks good or not but I have not applied that picture.

**Comment by sumitkr2000** [comment]
Hey, @Susmita-Dey I have successfully resolved the merge conflicts. I have solved the issue that I stated above. Please review my pull request. Thank you!

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Comment by sumitkr2000** [comment]
LGTM??

**Pull request merged**
