### PR TITLE
Footer content center align on larger screen

### PR DESCRIPTION
**Pull request by ramanujamgond**
By including the mx-auto class, the footer content is made center aligned on bigger screens.

### CODE REVIEW

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
@ramanujamgond Fix merge conflicts

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Comment by Susmita-Dey** [comment]
@ramanujamgond Mention the issue no you're assigned to make this PR and also attach a ss. After that I'll merge it.

**Comment by ramanujamgond** [comment]
@Susmita-Dey - The issue number is #124 

image

**Comment by Susmita-Dey** [comment]
@ramanujamgond I asked for the issue number, not the PR number. Also, the thing which you want to fix, it's already fixed and it's there in the website. So, this seems to be a spam PR. Closing it.

**Comment by ramanujamgond** [comment]
@Susmita-Dey - Without reviewing the code, it is not a good idea to draw any conclusions. Although I verified the code on your website, the problem is still present there. The footer on your website is not correctly centered and aligned when viewed at 1920x1080 resolution. I'm sending you the screenshot so you can refer to it. Additionally, I'm having some problems locating the issue number. And your reply's tone bothers me because I think it's quite impolite. With this response, I have lost interest in helping with your project.

Screenshot-2022-10-16-192317

**Pull request closed without merging**
