### PR TITLE
Updated and Linked professional footer UI designing

### PR DESCRIPTION
**Pull request by fykaa**
Hii @Susmita-Dey !
✔️Added some interesting footer design UI with hover effect and added animations. Hope you like it :) Thank you!
✔️And added footer's logo css to the top for improving UI
✔️Also linked your socials :)
image

image

image

image

### CODE REVIEW

**Comment by Vanshiii203** [comment]
@fykaa 

But this issue was not assigned to you. I am working on this issue.

**Comment by fykaa** [comment]
Hello, @Vanshiii203  I contributed for the Hacktoberfest; ig it does not necessarily imply issues; I just performed the PR that I believed needed to be improved; that is what the Hacktoberfest was intended for. You may still make your desired modifications because this is an enhancement PR and not a bug repair.

**Comment by fykaa** [comment]
@Susmita-Dey Updated changes to the Design as such -
image

image

Also Added Flip Animation :)

**Comment by Susmita-Dey** [comment]
@fykaa Don't make PRs directly like this. Issue needs to be made and then after i assign you, you can make a PR.

**Pull request closed without merging**
