### PR TITLE
style: addition of a transition on mouse-over

### PR DESCRIPTION
**Pull request by MoskalykA**

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@MoskalykA issue no?

**Comment by MoskalykA** [comment]
> @MoskalykA issue no?

no

**Comment by Susmita-Dey** [comment]
@MoskalykA What do you mean by "no"? Haven't you made any issues?

**Comment by MoskalykA** [comment]
> @MoskalykA What do you mean by "no"? Haven't you made any issues?

It's just a proposal and it's not related to a problem.

**Comment by Susmita-Dey** [comment]
@MoskalykA Fix mege conflicts, update your branch and create a feature request issue and get assigned first and then link the issue no here in this PR.

**Comment by MoskalykA** [comment]
> @MoskalykA Fix mege conflicts, update your branch and create a feature request issue and get assigned first and then link the issue no here in this PR.

https://github.com/Susmita-Dey/Moody-website/issues/66

**Pull request closed without merging**
