### PR TITLE
updated testimonials

### PR DESCRIPTION
**Pull request by sanathan-git**
In Testimonials section added border-radius and shadow to the divs

CHANGES MADE :-  rounded - rounded-3xl shadow-2xl

Thank you[🌻](https://emojipedia.org/sunflower/)

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@sanathan-git issue no?

**Comment by imaaquibali** [comment]
@sanathan-git mention your issue number and resolve the conflict!

**Comment by imaaquibali** [comment]
@Susmita-Dey @sanathan-git  is not responding. pr close kr du

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey @sanathan-git is not responding. pr close kr du

Wait for some more days

**Comment by sanathan-git** [comment]
Solved merge confilcts 
The issue I wanted to resolve already solved 
Thank you ✿

**Comment by Susmita-Dey** [comment]
@sanathan-git Is it already in the website? Or it will be solved via this PR?

**Pull request closed without merging**
