### PR TITLE
Hover Effects

### PR DESCRIPTION
**Pull request by Aman0786-git**
### Hover Effets In #7 
- Nav Button
- Header Buttons
- Contact Section Button
- Hover Color Changed in Nav Items

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@Aman0786-git add an ss or video

**Comment by Aman0786-git** [comment]
> 

moody1
moody2
moody3

**Comment by Aman0786-git** [comment]
@Susmita-Dey Updated

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
