### PR TITLE
remove the extra space in the footer

### PR DESCRIPTION
**Pull request by imaaquibali**
fix issue #105

### CODE REVIEW

**Comment by imaaquibali** [comment]
@Susmita-Dey have a look on it.

**Comment by Susmita-Dey** [comment]
@imaaquibali fix merge conflicts

**Comment by imaaquibali** [comment]
@Susmita-Dey Resolved! Have a look at it.

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
After resolving merge conflicts, there's no changes in your PR. Kindly check it.

**Comment by imaaquibali** [comment]
> After resolving merge conflicts, there's no changes in your PR. Kindly check it.

Someone already solve the issue!

**Pull request closed without merging**
