### PR TITLE
Bottom to Top button has been added

### PR DESCRIPTION
**Pull request by Anubhavgupta14**
Bottom to Top button has been added.
Issue Solved :- #84 
ScreenShot:-

@Susmita-Dey Kindly Review it and if found good then I request you to merge it.

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@Anubhavgupta14 Update your branch and ping me on discord

**Comment by imaaquibali** [comment]
@Anubhavgupta14 Fix the merge conflict

**Comment by Anubhavgupta14** [comment]
@Susmita-Dey Now, Code is Updated. KIndly merge it.

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
