### PR TITLE
Hover Effect in Nav Bar items and Buttons

### PR DESCRIPTION
**Pull request by Aman0786-git**
### Added Hover and Transformation Effect #7  
- In navbar itemns
- Hero Section buttons
- Contact Section button

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@Aman0786-git Fix merge conflicts

**Comment by imaaquibali** [comment]
@Susmita-Dey Should i close this PR?

**Comment by Susmita-Dey** [comment]
> @Susmita-Dey Should i close this PR?

Let's wait for few more days

**Comment by Aman0786-git** [comment]
> > @Susmita-Dey Should i close this PR?
> 
> Let's wait for few more days

Code base changed a lot after that so I have to re work on this issue so if you want I can make another PR for that

**Comment by Susmita-Dey** [comment]
@Aman0786-git Closing this PR so that you can make a new PR.

**Pull request closed without merging**
