### PR TITLE
Changed Footer UI

### PR DESCRIPTION
**Pull request by YasirObaibullah99**
With the reference to #35

### CODE REVIEW

**Comment by imaaquibali** [comment]
@YasirObaibullah99 Can you please attached your PR video?

**Comment by YasirObaibullah99** [comment]
@imaaquibali This is the video
[Screencast from 05-10-22 09:32:15 PM IST.webm](https://user-images.githubusercontent.com/83706868/194107884-907c41d2-bce7-4fad-9257-ac57f97473a6.webm)

**Comment by imaaquibali** [comment]
@YasirObaibullah99 Brother it taking too much footer space.

**Comment by YasirObaibullah99** [comment]
But it's looking good brother

**Pull request merged**
