### PR TITLE
Testimonials Header Introduced

### PR DESCRIPTION
**Pull request by qasim0014**

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@qasim0014 Issue no?

**Comment by qasim0014** [comment]
> @qasim0014 Issue no?

I am sorry, do I have to report it as an issue first?

**Comment by Susmita-Dey** [comment]
> I am sorry, do I have to report it as an issue first?

Yes

**Comment by qasim0014** [comment]
> > I am sorry, do I have to report it as an issue first?
> 
> Yes

Acknowledged

**Comment by qasim0014** [comment]
#49

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

**Comment by Susmita-Dey** [comment]
@qasim0014 Kindly pull recent changes.

**Comment by qasim0014** [comment]
> @qasim0014 Kindly pull recent changes. I mean to say update your branch.

@Susmita-Dey branch rebased

**Review by Susmita-Dey — APPROVED** [review]
Good job.

**Pull request merged**
