### PR TITLE
Contact Us Form Fix

### LINKED ISSUE #52: Restrict empty contact-us form submission
### Description

Form can be submitted without entering the email or content in the form.

### Screenshots

image
image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by AbhishekJadhav2002**
Added validations on form submissions like,
- Email Validations
- Non-empty Name field
- Catching networking errors
- Showing descriptive feedback on the UI

Accomplished by writting a submitForm() function in [script.js](https://github.com/AbhishekJadhav2002/Moody-website/blob/066f9d59e9ce1a0fc39f5cdb505b1c148cd4887e/script.js#L35) which will be called when user click on Submit button.

Note - 

> [This](https://github.com/AbhishekJadhav2002/Moody-website/commit/deaa3d214d43d92e6bae65ad66a20da144ebe9e4) additional commit was done to resolve the merge conflict which doen not breaks the working of any code.

### Screenshot
image
fixes #52

### CODE REVIEW

**Comment by AbhishekJadhav2002** [comment]
@Susmita-Dey will you check once. Please suggest changes, if any.
> Successfully merging this pull request may close #52 issue.

**Comment by imaaquibali** [comment]
@AbhishekJadhav2002 can you please send the video of ur PR?

**Review by imaaquibali — APPROVED** [review]

**Comment by AbhishekJadhav2002** [comment]
> @AbhishekJadhav2002 can you please send the video of ur PR?

Yes, here is what I have done in my PR.

https://user-images.githubusercontent.com/79781388/194280172-725d3d0f-c8d8-4b0b-8f43-192a19d788ec.mp4
> Development server running on `http://127.0.0.1:5500/`

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Fix merge conflicts

**Review by AbhishekJadhav2002 — COMMENTED** [review]
Done

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
The bg image of contact us section has been changed. Kindly check it and do the same for this PR.

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
