### PR TITLE
Added issue_template for bug

### LINKED ISSUE #23: Add issue templates
I think we can add some issue templates for this project so anyone can easily share their issue

### PR DESCRIPTION
**Pull request by Niravprajapati1**
Fix #23

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@Niravprajapati1 Add `others` and `new feature request`

**Comment by Niravprajapati1** [comment]
Sure it's my pleasure 🙂

**Comment by Niravprajapati1** [comment]
Anything else I can do?

**Review by Susmita-Dey — APPROVED** [review]
Good job.

**Comment by Niravprajapati1** [comment]
Thanks 👍

**Pull request merged**
