### PR TITLE
Grammatical error in Testimonials #71

### PR DESCRIPTION
**Pull request by sethisagar**

### CODE REVIEW

**Review by Susmita-Dey — COMMENTED** [review]
You only added a space and nothing else. This is kinda spam PR.

**Comment by sethisagar** [comment]
@Susmita-Dey but @imaaquibali agreed to fix this, you can check the issue #71.
You marked it Spam, that's not good.

**Comment by sethisagar** [comment]
This is the result what you did

**Comment by sethisagar** [comment]
How you can say its a spam? 
A bug is a bug what ever it is. 
And bug was approved.

**Comment by Susmita-Dey** [comment]
@sethisagar Sorry for the inconvinience. Thanks for your contribution.

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
