### PR TITLE
Updated the responsiveness of moody-website.

### PR DESCRIPTION
**Pull request by surbhi400**
The Buy me a coffee button was overlapping its text for extra small devices so I updated the responsiveness for extra small devices. 

fixes issue no #75 

Earlier it used to look like this-
moody-website-update

Now it look like this-
moody(1)

moody(2)

### CODE REVIEW

**Comment by surbhi400** [comment]
@Susmita-Dey please review my PR.

**Comment by Susmita-Dey** [comment]
@surbhi400 Update your branch

**Comment by surbhi400** [comment]
@Susmita-Dey do you mean that i need to change my branch name?

**Comment by surbhi400** [comment]
@Susmita-Dey Its done. please review it again.

**Comment by Susmita-Dey** [comment]
@surbhi400 Can you update again for the last time?

**Comment by surbhi400** [comment]
@Susmita-Dey Actually I am getting quite confused with what I really have to do. MY branch isn't showing any conflict with the main branch. Do I have to change the name of my branch. Could you explain in a little detail.

**Comment by Susmita-Dey** [comment]
@surbhi400 Are you able to see this kind of thing in this PR by scrolling down?

image

> If yes, then click on that button to update your branch.

**Comment by surbhi400** [comment]
@Susmita-Dey its done, please check it.

**Review by Susmita-Dey — APPROVED** [review]
Thanks for your awesome contribution

**Pull request merged**
