### PR TITLE
enhanced home page

### PR DESCRIPTION
**Pull request by Vanshiii203**
issue #8 

https://user-images.githubusercontent.com/94471189/193454914-0fc9c962-8847-4f30-8be7-91c228f87afa.mp4

### CODE REVIEW

**Comment by Susmita-Dey** [comment]
@Vanshiii203 fix merge conflicts

**Comment by Vanshiii203** [comment]
> @Vanshiii203 fix merge conflicts

done

**Comment by Susmita-Dey** [comment]
@Vanshiii203 Is the branch updated?

**Comment by Vanshiii203** [comment]
> @Vanshiii203 Is the branch updated?

yes

**Review by Susmita-Dey — APPROVED** [review]
Good job.

**Pull request merged**
